version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3011:3000" # 可选，暴露Node.js端口

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:80" # 暴露Nginx端口
    depends_on:
      - node